# Generated by Django 5.1.4 on 2025-03-11 13:30

import PaymentSystem.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('cash', models.IntegerField(default=0)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('admin', 'Admin')], default='client', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=(models.Model, PaymentSystem.models.TransactionValidationMixin),
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_card_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('virtual_card_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit_cash', 'Dépôt en espèces'), ('deposit_momo', 'Dépôt'), ('withdraw_cash', 'Retrait en espèces'), ('withdraw_momo', 'Retrait'), ('payment', 'Paiement marchand'), ('transfer', 'Transfert')], max_length=20)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_internal_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_internal_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalWithdrawalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit_cash', 'Dépôt en espèces'), ('deposit_momo', 'Dépôt'), ('withdraw_cash', 'Retrait en espèces'), ('withdraw_momo', 'Retrait'), ('payment', 'Paiement marchand'), ('transfer', 'Transfert')], max_length=20)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('operator_code', models.CharField(choices=[('OM_SN_CASHIN', 'Orange Money Cashin SN'), ('OM_SN_CASHOUT', 'Orange Money Cashout SN'), ('WAVE_SN_CASHOUT', 'Wave Cashout SN'), ('WAVE_SN_CASHIN', 'Wave Cashin SN'), ('FM_SN_CASHIN', 'Free Money Cashin SN'), ('FM_SN_CASHOUT', 'Free Money Cashout SN'), ('WIZALL_SN_CASHOUT', 'Wizall Money Cashout SN'), ('WIZALL_SN_CASHIN', 'Wizall Money Cashin SN')], max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('receiver', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_external_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalDepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit_cash', 'Dépôt en espèces'), ('deposit_momo', 'Dépôt'), ('withdraw_cash', 'Retrait en espèces'), ('withdraw_momo', 'Retrait'), ('payment', 'Paiement marchand'), ('transfer', 'Transfert')], max_length=20)),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('operator_code', models.CharField(choices=[('OM_SN_CASHIN', 'Orange Money Cashin SN'), ('OM_SN_CASHOUT', 'Orange Money Cashout SN'), ('WAVE_SN_CASHOUT', 'Wave Cashout SN'), ('WAVE_SN_CASHIN', 'Wave Cashin SN'), ('FM_SN_CASHIN', 'Free Money Cashin SN'), ('FM_SN_CASHOUT', 'Free Money Cashout SN'), ('WIZALL_SN_CASHOUT', 'Wizall Money Cashout SN'), ('WIZALL_SN_CASHIN', 'Wizall Money Cashin SN')], max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sender', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_external_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
