# Generated by Django 5.1.4 on 2025-01-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('gérant', 'Gérant'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
