# Generated by Django 5.1.4 on 2026-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='last_sdm_counter',
            field=models.PositiveIntegerField(default=0, help_text='Last seen SDM read counter for anti-replay'),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='sdm_aes_key',
            field=models.CharField(blank=True, help_text='AES-128 key (hex) for DESFire EV3 SDM verification', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='externaldeposittransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='externalwithdrawaltransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='internaltransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UsedNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=36, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['used_at'], name='PaymentSyst_used_at_80572c_idx')],
            },
        ),
    ]
