# Generated by Django 5.1.4 on 2025-01-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0003_alter_customuser_user_type_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
