# Generated by Django 5.1.4 on 2025-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0004_alter_customuser_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
