# Generated by Django 5.1.4 on 2025-02-09 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0009_alter_externaldeposittransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='virtual_card_identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
