# Generated by Django 5.1.4 on 2025-02-10 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0010_nfccard_virtual_card_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfccard',
            old_name='account_number',
            new_name='physical_card_token',
        ),
        migrations.RemoveField(
            model_name='nfccard',
            name='manufacturer_identifier',
        ),
        migrations.RemoveField(
            model_name='nfccard',
            name='virtual_card_identifier',
        ),
        migrations.AddField(
            model_name='nfccard',
            name='virtual_card_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
