# Generated by Django 5.1.4 on 2025-02-13 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentSystem', '0011_rename_account_number_nfccard_physical_card_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='physical_card_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='virtual_card_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
